# Generated by Django 4.2.4 on 2023-09-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cbr', models.CharField(max_length=10, verbose_name='ID_CBR', unique=True)),
                ('num_code', models.CharField(max_length=5, verbose_name='cbr_num_code', unique=True)),
                ('char_code', models.CharField(max_length=5, verbose_name='cbr_char_code')),
                ('name', models.CharField(max_length=100, verbose_name='Currency name')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField(default=1, verbose_name='Nominal')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_rate', to='exchange_rates.currency')),
            ],
        ),
    ]
