# Generated by Django 4.2.4 on 2023-09-22 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange_rates', '0002_alter_dailyrate_options_usercurrency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercurrency',
            unique_together={('user', 'currency')},
        ),
    ]
